---
 - name: Change Linuxadm Password
   hosts: Password
   gather_facts: false
   ignore_errors: true
   tasks: 
    - name: change linuxadm password
      ansible.builtin.user:
        name: linuxadm
        state: present
        password: "{{ newpassword|password_hash('sha512') }}"
